fix(visibility): Reset visibility
Powback/VEManager pull request #33
Opened 2022-02-25 09:55 UTC by FlashHit

2022-02-25 16:13 UTC, IllustrisJack requested changes
this and merge

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +		local b = self.m_Presets[p_Id].startValue
p_ID

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +function VEManagerClient:ResetVisibility(p_ID, p_Visibility)
SetVisibility()

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +	self:SetVisibility(p_ID, p_Visibility)
SetVisibilityInternal()

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +	for p_Id, _ in pairs(self.m_Lerping) do
l_ID

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +		local TimeSinceStarted = SharedUtils:GetTimeMS() - self.m_Presets[p_Id].startTime
l_ID

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +		local PercentageComplete = TimeSinceStarted / self.m_Presets[p_Id].time
l_ID

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +		local c = self.m_Presets[p_Id].EndValue - self.m_Presets[p_Id].startValue
l_ID and so on

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +			self:SetVisibility(p_Id, lerpValue)
SetVisibilityInternal()

2022-02-25 16:13 UTC, IllustrisJack commented on ext/Client/__init__.lua
>  function VEManagerClient:SetVisibility(p_ID, p_Visibility)
SetVisibilityInternal()

2022-02-25 16:19 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +			self:SetVisibility(p_Id, lerpValue)
p_ID

2022-02-25 16:23 UTC, IllustrisJack commented on ext/Client/__init__.lua
> +	Events:Subscribe('VEManager:ResetVisibility', self, self.ResetVisibility)
obsolete after review changes

2022-02-27 01:04 UTC, 3ti65 approved these changes

2022-02-27 01:04 UTC, merged